POST https://javascriptmas.cyclic.app/api/post/
Content-Type: application/json

{
    "number": 11,
    "available": true
}
###
GET https://javascriptmas.cyclic.app/api/getAll/

###
GET https://javascriptmas.cyclic.app/api/users/
###

GET https://javascriptmas.cyclic.app/api/getOne/639b361aff0b7f81809cfaa5
###
PATCH https://javascriptmas.cyclic.app/api/update/639b361aff0b7f81809cfaa5
Content-Type: application/json

{
    "available": true
}
###

POST https://javascriptmas.cyclic.app/api/users/
Content-Type: application/json

{
    "firstName": "test1",
    "lastName": "lastname",
    "email": "test@yahoo.com",
    "username": "nas2",
    "password": "12345"
}
###

GET https://javascriptmas.cyclic.app/api/appointments/2022-12-29
###

POST https://javascriptmas.cyclic.app/api/users/gs
Content-Type: application/json

{
    "password": "password"
}
###
GET https://javascriptmas.cyclic.app/api/appointments/

###
PATCH  https://javascriptmas.cyclic.app/api/appointments/63a433493e4a7dab54e4c6fc
Content-Type: application/json

{
    "username": "nb",
    "available": 0
}

###
POST https://javascriptmas.cyclic.app/api/payment
Content-Type: application/json

{
    
}

###
GET https://localhost/:3000/api/appointments/